"""initial route workflow"""

import sqlalchemy as sa
from alembic import op

revision = "d69981b76ed6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("profile_id", sa.String(length=50), nullable=False),
        sa.Column("study_uid", sa.String(length=128), nullable=False),
        sa.Column("encounter_ref", sa.String(length=128), nullable=False),
        sa.Column("patient_token", sa.String(length=36), nullable=False),
        sa.Column("modality", sa.String(length=30), nullable=False),
        sa.Column("published_route_id", sa.String(length=36), nullable=True),
        sa.Column("pending_review", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "study_uid"),
    )
    op.create_table(
        "commands",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=150), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "token"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_events_case_id"), "events", ["case_id"], unique=False)
    op.create_index(op.f("ix_events_kind"), "events", ["kind"], unique=False)
    op.create_table(
        "source_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("source_version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("source_kind", sa.String(length=20), nullable=False),
        sa.Column("canonical", sa.JSON(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "source_version"),
    )
    op.create_index(op.f("ix_source_reports_case_id"), "source_reports", ["case_id"], unique=False)
    op.create_table(
        "route_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("case_id", sa.String(length=36), nullable=False),
        sa.Column("report_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("ruleset_version", sa.String(length=60), nullable=False),
        sa.Column("proposed_steps", sa.JSON(), nullable=False),
        sa.Column("steps", sa.JSON(), nullable=False),
        sa.Column("trace", sa.JSON(), nullable=False),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["cases.id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["source_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("case_id", "version"),
    )
    op.create_index(op.f("ix_route_versions_case_id"), "route_versions", ["case_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("route_id", sa.String(length=36), nullable=False),
        sa.Column("step_key", sa.String(length=50), nullable=False),
        sa.Column("service_id", sa.String(length=100), nullable=False),
        sa.Column("slot", sa.String(length=100), nullable=False),
        sa.Column("slot_key", sa.String(length=250), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slot_key"),
    )
    op.create_index(op.f("ix_bookings_route_id"), "bookings", ["route_id"], unique=False)
    op.create_table(
        "clinical_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("route_id", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.String(length=2000), nullable=False),
        sa.Column("original_steps", sa.JSON(), nullable=False),
        sa.Column("final_steps", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id"),
    )
    op.create_table(
        "step_results",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("route_id", sa.String(length=36), nullable=False),
        sa.Column("step_key", sa.String(length=50), nullable=False),
        sa.Column("outcome", sa.String(length=30), nullable=False),
        sa.Column("note", sa.String(length=2000), nullable=False),
        sa.Column("created_at", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["route_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_id", "step_key"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("step_results")
    op.drop_table("clinical_decisions")
    op.drop_index(op.f("ix_bookings_route_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_route_versions_case_id"), table_name="route_versions")
    op.drop_table("route_versions")
    op.drop_index(op.f("ix_source_reports_case_id"), table_name="source_reports")
    op.drop_table("source_reports")
    op.drop_index(op.f("ix_events_kind"), table_name="events")
    op.drop_index(op.f("ix_events_case_id"), table_name="events")
    op.drop_table("events")
    op.drop_table("commands")
    op.drop_table("cases")
    # ### end Alembic commands ###
